batch_size: 100
checkpoint_interval: 500
chunk_max_tokens: 512
chunk_overlap: 50
coherence_threshold: 0.4
embed_model: sentence-transformers/all-MiniLM-L6-v2
enable_monitoring: true
log_level: INFO
max_retries: 3
max_text_length: 5000
min_text_length: 100
offline_mode: false
ood_ratio: 0.2
output_dir: ./thinkerbell_output
parallel_workers: 4
samples_target: 500
save_diagnostics: true
save_intermediate: true
style_profiles_dir: ./style_profiles
templates_dir: ./Thinkerbell_template_pipeline/thinkerbell/data
tokenizer_model: sentence-transformers/all-MiniLM-L6-v2
validation_strict: false
